name: sehrimapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # IMAGE PICKER (tek kez!)
  image_picker: ^1.2.1

  # Firebase (birbirleriyle uyumlu sürümler)
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4

  # Google Maps & Location
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  # Image Processing & Network Images
  image: ^4.1.7
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2

  # UI & Animations
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.0

  # State Management
  provider: ^6.1.2

  # Utilities
  shared_preferences: ^2.5.3
  share_plus: ^7.2.1
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
